### ISSUE TITLE
GRPC: No connection established

### ISSUE THREAD

**Issue by tc-developer01** [findy-network/findy-issuer-tool#130]
Hello,

we tried running findy-issuer-tool and ran into the GRPC error `No connection established`, see error output in spoiler tag below.

We have successfully:

- Launched [backend services and wallet](https://github.com/findy-network/findy-wallet-pwa/tree/dev/tools/env#agency-setup-for-local-development) from `findy-wallet-pwa`
    - We can reach localhost:3000 for wallet and localhost:8088 for "OK"
- Followed steps from `findy-issuer-tool`
    - Installed dependencies via `npm install` in `findy-issuer-tool/api`
    - using default config (default.json)
    - Started `npm run db`
    - Set `export AWS_ACCESS_KEY_ID="foo"` and `export AWS_SECRET_ACCESS_KEY="bar"`

But then `npm start` in `findy-issuer-tool/api` fails:

<details>
  <summary>Error log after npm start</summary>

```
~/findy-issuer-tool/api$ npm start

> issuer-tool@0.2.4 start
> npm run init:keys && npm run build && node ./build/index.js


> issuer-tool@0.2.4 init:keys
> cd tools/isb && ./download-keys.sh

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1679  100  1679    0     0   4250      0 --:--:-- --:--:-- --:--:--  4250
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1678  100  1678    0     0   6101      0 --:--:-- --:--:-- --:--:--  6101

> issuer-tool@0.2.4 build
> rimraf build/ && babel ./src --out-dir build/ --ignore **/*.test.js

Successfully compiled 20 files with Babel (932ms).
D 2022-05-18T12:59:09.814Z | index | Loading @grpc/grpc-js version 1.5.10
[2022-05-18T12:59:10.401Z] info: AWS dynamodb config endpoint http://localhost:8000
[2022-05-18T12:59:10.409Z] info: Creating dynamodb storage
[2022-05-18T12:59:10.433Z] warn: Unable to create table.
[2022-05-18T12:59:10.434Z] info: Connecting to agency address localhost, port 50052, cert , verifyServer true
[2022-05-18T12:59:10.550Z] info: Agent login succeeded with first try.
D 2022-05-18T12:59:10.562Z | resolving_load_balancer | dns:localhost:50052 IDLE -> IDLE
D 2022-05-18T12:59:10.563Z | connectivity_state | (1) dns:localhost:50052 IDLE -> IDLE
D 2022-05-18T12:59:10.563Z | dns_resolver | Resolver constructed for target dns:localhost:50052
D 2022-05-18T12:59:10.564Z | channel | (1) dns:localhost:50052 Channel constructed with options {}
D 2022-05-18T12:59:10.564Z | channel_stacktrace | (1) Channel constructed 
    at new ChannelImplementation ([...]/findy-issuer-tool/api/node_modules/@grpc/grpc-js/build/src/channel.js:197:23)
    at new Client ([...]/findy-issuer-tool/api/node_modules/@grpc/grpc-js/build/src/client.js:62:36)
    at new ServiceClientImpl ([...]/findy-issuer-tool/api/node_modules/@grpc/grpc-js/build/src/make-client.js:58:5)
    at [...]/findy-issuer-tool/api/node_modules/@findy-network/findy-common-ts/dist/grpc/index.js:88:46
    at step ([...]/findy-issuer-tool/api/node_modules/@findy-network/findy-common-ts/dist/grpc/index.js:33:23)
    at Object.next ([...]/findy-issuer-tool/api/node_modules/@findy-network/findy-common-ts/dist/grpc/index.js:14:53)
    at [...]/findy-issuer-tool/api/node_modules/@findy-network/findy-common-ts/dist/grpc/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter ([...]/findy-issuer-tool/api/node_modules/@findy-network/findy-common-ts/dist/grpc/index.js:4:12)
    at createAgentClient ([...]/findy-issuer-tool/api/node_modules/@findy-network/findy-common-ts/dist/grpc/index.js:82:62)
D 2022-05-18T12:59:10.565Z | resolving_load_balancer | dns:localhost:50052 IDLE -> IDLE
D 2022-05-18T12:59:10.565Z | connectivity_state | (2) dns:localhost:50052 IDLE -> IDLE
D 2022-05-18T12:59:10.565Z | dns_resolver | Resolver constructed for target dns:localhost:50052
D 2022-05-18T12:59:10.566Z | channel | (2) dns:localhost:50052 Channel constructed with options {}
D 2022-05-18T12:59:10.566Z | channel_stacktrace | (2) Channel constructed 
    at new ChannelImplementation ([...]/findy-issuer-tool/api/node_modules/@grpc/grpc-js/build/src/channel.js:197:23)
    at new Client ([...]/findy-issuer-tool/api/node_modules/@grpc/grpc-js/build/src/client.js:62:36)
    at new ServiceClientImpl ([...]/findy-issuer-tool/api/node_modules/@grpc/grpc-js/build/src/make-client.js:58:5)
    at [...]/findy-issuer-tool/api/node_modules/@findy-network/findy-common-ts/dist/grpc/index.js:100:46
    at step ([...]/findy-issuer-tool/api/node_modules/@findy-network/findy-common-ts/dist/grpc/index.js:33:23)
    at Object.next ([...]/findy-issuer-tool/api/node_modules/@findy-network/findy-common-ts/dist/grpc/index.js:14:53)
    at [...]/findy-issuer-tool/api/node_modules/@findy-network/findy-common-ts/dist/grpc/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter ([...]/findy-issuer-tool/api/node_modules/@findy-network/findy-common-ts/dist/grpc/index.js:4:12)
    at createProtocolClient ([...]/findy-issuer-tool/api/node_modules/@findy-network/findy-common-ts/dist/grpc/index.js:94:65)
[2022-05-18T12:59:10.577Z] info: FTN credDefId: undefined
D 2022-05-18T12:59:10.583Z | channel | (1) dns:localhost:50052 createCall [0] method="/agency.v1.AgentService/Listen", deadline=Infinity
D 2022-05-18T12:59:10.584Z | call_stream | [0] Sending metadata
D 2022-05-18T12:59:10.584Z | dns_resolver | Looking up DNS hostname localhost
D 2022-05-18T12:59:10.584Z | resolving_load_balancer | dns:localhost:50052 IDLE -> CONNECTING
D 2022-05-18T12:59:10.584Z | connectivity_state | (1) dns:localhost:50052 IDLE -> CONNECTING
D 2022-05-18T12:59:10.585Z | resolving_load_balancer | dns:localhost:50052 CONNECTING -> CONNECTING
D 2022-05-18T12:59:10.585Z | connectivity_state | (1) dns:localhost:50052 CONNECTING -> CONNECTING
D 2022-05-18T12:59:10.585Z | channel | (1) dns:localhost:50052 callRefTimer.ref | configSelectionQueue.length=1 pickQueue.length=0
D 2022-05-18T12:59:10.585Z | call_stream | [0] write() called with message of length 38
D 2022-05-18T12:59:10.585Z | call_stream | [0] end() called
D 2022-05-18T12:59:10.587Z | call_stream | [0] deferring writing data chunk of length 43
D 2022-05-18T12:59:10.587Z | dns_resolver | Resolved addresses for target dns:localhost:50052: [127.0.0.1:50052]
D 2022-05-18T12:59:10.588Z | pick_first | Connect to address list 127.0.0.1:50052
D 2022-05-18T12:59:10.589Z | subchannel | (3) 127.0.0.1:50052 Subchannel constructed with options {}
D 2022-05-18T12:59:10.589Z | subchannel_refcount | (3) 127.0.0.1:50052 refcount 0 -> 1
D 2022-05-18T12:59:10.589Z | subchannel_refcount | (3) 127.0.0.1:50052 refcount 1 -> 2
D 2022-05-18T12:59:10.589Z | pick_first | Start connecting to subchannel with address 127.0.0.1:50052
D 2022-05-18T12:59:10.589Z | pick_first | IDLE -> CONNECTING
D 2022-05-18T12:59:10.589Z | resolving_load_balancer | dns:localhost:50052 CONNECTING -> CONNECTING
D 2022-05-18T12:59:10.589Z | channel | (1) dns:localhost:50052 callRefTimer.unref | configSelectionQueue.length=1 pickQueue.length=0
D 2022-05-18T12:59:10.589Z | connectivity_state | (1) dns:localhost:50052 CONNECTING -> CONNECTING
D 2022-05-18T12:59:10.589Z | subchannel | (3) 127.0.0.1:50052 IDLE -> CONNECTING
D 2022-05-18T12:59:10.590Z | pick_first | CONNECTING -> CONNECTING
D 2022-05-18T12:59:10.590Z | resolving_load_balancer | dns:localhost:50052 CONNECTING -> CONNECTING
D 2022-05-18T12:59:10.590Z | connectivity_state | (1) dns:localhost:50052 CONNECTING -> CONNECTING
D 2022-05-18T12:59:10.590Z | channel | (1) dns:localhost:50052 Pick result for call [0]: QUEUE subchannel: null status: undefined undefined
D 2022-05-18T12:59:10.590Z | channel | (1) dns:localhost:50052 callRefTimer.ref | configSelectionQueue.length=0 pickQueue.length=1
D 2022-05-18T12:59:10.591Z | subchannel | (3) 127.0.0.1:50052 creating HTTP/2 session
[2022-05-18T12:59:10.602Z] info: Creating default cred defs...
[2022-05-18T12:59:10.602Z] info: Creating schema {"name":"github","version":"1.0","attrs":["id","name","email"]}
[2022-05-18T12:59:10.604Z] info: Creating schema {"name":"ftn","version":"1.0","attrs":["name","given_name","family_name","birthdate","personal_identity_code","auth_time"]}
D 2022-05-18T12:59:10.605Z | channel | (1) dns:localhost:50052 createCall [1] method="/agency.v1.AgentService/CreateSchema", deadline=Infinity
D 2022-05-18T12:59:10.605Z | call_stream | [1] Sending metadata
D 2022-05-18T12:59:10.605Z | channel | (1) dns:localhost:50052 Pick result for call [1]: QUEUE subchannel: null status: undefined undefined
D 2022-05-18T12:59:10.606Z | call_stream | [1] write() called with message of length 30
D 2022-05-18T12:59:10.606Z | call_stream | [1] end() called
D 2022-05-18T12:59:10.606Z | channel | (1) dns:localhost:50052 createCall [2] method="/agency.v1.AgentService/CreateSchema", deadline=Infinity
D 2022-05-18T12:59:10.606Z | call_stream | [2] Sending metadata
D 2022-05-18T12:59:10.606Z | channel | (1) dns:localhost:50052 Pick result for call [2]: QUEUE subchannel: null status: undefined undefined
D 2022-05-18T12:59:10.606Z | call_stream | [2] write() called with message of length 87
D 2022-05-18T12:59:10.606Z | call_stream | [2] end() called
D 2022-05-18T12:59:10.606Z | call_stream | [1] deferring writing data chunk of length 35
D 2022-05-18T12:59:10.606Z | call_stream | [2] deferring writing data chunk of length 92
D 2022-05-18T12:59:10.619Z | subchannel | (3) 127.0.0.1:50052 connection closed with error self signed certificate
D 2022-05-18T12:59:10.619Z | subchannel | (3) 127.0.0.1:50052 connection closed
D 2022-05-18T12:59:10.619Z | subchannel | (3) 127.0.0.1:50052 CONNECTING -> TRANSIENT_FAILURE
D 2022-05-18T12:59:10.619Z | pick_first | CONNECTING -> TRANSIENT_FAILURE
D 2022-05-18T12:59:10.619Z | resolving_load_balancer | dns:localhost:50052 CONNECTING -> TRANSIENT_FAILURE
D 2022-05-18T12:59:10.619Z | channel | (1) dns:localhost:50052 callRefTimer.unref | configSelectionQueue.length=0 pickQueue.length=0
D 2022-05-18T12:59:10.619Z | channel | (1) dns:localhost:50052 Pick result for call [0]: TRANSIENT_FAILURE subchannel: null status: 14 No connection established
D 2022-05-18T12:59:10.619Z | call_stream | [0] cancelWithStatus code: 14 details: "No connection established"
D 2022-05-18T12:59:10.620Z | call_stream | [0] ended with status: code=14 details="No connection established"
D 2022-05-18T12:59:10.620Z | channel | (1) dns:localhost:50052 Pick result for call [1]: TRANSIENT_FAILURE subchannel: null status: 14 No connection established
D 2022-05-18T12:59:10.620Z | call_stream | [1] cancelWithStatus code: 14 details: "No connection established"
D 2022-05-18T12:59:10.620Z | call_stream | [1] ended with status: code=14 details="No connection established"
D 2022-05-18T12:59:10.620Z | channel | (1) dns:localhost:50052 Pick result for call [2]: TRANSIENT_FAILURE subchannel: null status: 14 No connection established
D 2022-05-18T12:59:10.620Z | call_stream | [2] cancelWithStatus code: 14 details: "No connection established"
D 2022-05-18T12:59:10.620Z | call_stream | [2] ended with status: code=14 details="No connection established"
D 2022-05-18T12:59:10.620Z | connectivity_state | (1) dns:localhost:50052 CONNECTING -> TRANSIENT_FAILURE
[2022-05-18T12:59:10.620Z] error: GRPC error when listening {"code":14,"details":"No connection established","metadata":{}}.
D 2022-05-18T12:59:10.620Z | call_stream | [0] cancelWithStatus code: 1 details: "Cancelled on client"
[2022-05-18T12:59:10.621Z] error: createSchema: GRPC error {"code":14,"details":"No connection established","metadata":{}}
[2022-05-18T12:59:10.621Z] error: createSchema: GRPC error {"code":14,"details":"No connection established","metadata":{}}
[2022-05-18T12:59:10.621Z] error: Streaming ended when listening.
D 2022-05-18T12:59:10.621Z | call_stream | [0] cancelWithStatus code: 1 details: "Cancelled on client"
[2022-05-18T12:59:10.621Z] error: Retry listening...
[2022-05-18T12:59:10.623Z] error: uncaughtException: 14 UNAVAILABLE: No connection established
Error: 14 UNAVAILABLE: No connection established
    at Object.callErrorFromStatus ([...]/findy-issuer-tool/api/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus ([...]/findy-issuer-tool/api/node_modules/@grpc/grpc-js/build/src/client.js:180:52)
    at Object.onReceiveStatus ([...]/findy-issuer-tool/api/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus ([...]/findy-issuer-tool/api/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at [...]/findy-issuer-tool/api/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
[2022-05-18T12:59:10.623Z] error: uncaughtException: 14 UNAVAILABLE: No connection established
Error: 14 UNAVAILABLE: No connection established
    at Object.callErrorFromStatus ([...]/findy-issuer-tool/api/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus ([...]/findy-issuer-tool/api/node_modules/@grpc/grpc-js/build/src/client.js:180:52)
    at Object.onReceiveStatus ([...]/findy-issuer-tool/api/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus ([...]/findy-issuer-tool/api/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at [...]/findy-issuer-tool/api/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
D 2022-05-18T12:59:10.624Z | channel | (1) dns:localhost:50052 createCall [3] method="/agency.v1.AgentService/Listen", deadline=Infinity
D 2022-05-18T12:59:10.624Z | call_stream | [3] Sending metadata
D 2022-05-18T12:59:10.624Z | channel | (1) dns:localhost:50052 Pick result for call [3]: TRANSIENT_FAILURE subchannel: null status: 14 No connection established
D 2022-05-18T12:59:10.624Z | call_stream | [3] cancelWithStatus code: 14 details: "No connection established"
D 2022-05-18T12:59:10.624Z | call_stream | [3] ended with status: code=14 details="No connection established"
D 2022-05-18T12:59:10.624Z | call_stream | [3] write() called with message of length 38
D 2022-05-18T12:59:10.624Z | call_stream | [3] end() called
D 2022-05-18T12:59:10.624Z | call_stream | [3] deferring writing data chunk of length 43
[2022-05-18T12:59:10.625Z] error: GRPC error when listening {"code":14,"details":"No connection established","metadata":{}}.
D 2022-05-18T12:59:10.625Z | call_stream | [3] cancelWithStatus code: 1 details: "Cancelled on client"
[2022-05-18T12:59:10.625Z] error: Streaming ended when listening.
D 2022-05-18T12:59:10.625Z | call_stream | [3] cancelWithStatus code: 1 details: "Cancelled on client"
[2022-05-18T12:59:10.625Z] error: Retry listening...
D 2022-05-18T12:59:11.590Z | subchannel | (3) 127.0.0.1:50052 TRANSIENT_FAILURE -> IDLE
D 2022-05-18T12:59:11.591Z | subchannel_refcount | (3) 127.0.0.1:50052 refcount 2 -> 1
D 2022-05-18T12:59:11.591Z | pick_first | TRANSIENT_FAILURE -> IDLE
D 2022-05-18T12:59:11.591Z | resolving_load_balancer | dns:localhost:50052 TRANSIENT_FAILURE -> IDLE
D 2022-05-18T12:59:11.591Z | connectivity_state | (1) dns:localhost:50052 TRANSIENT_FAILURE -> IDLE
D 2022-05-18T12:59:15.629Z | channel | (1) dns:localhost:50052 createCall [4] method="/agency.v1.AgentService/Listen", deadline=Infinity
D 2022-05-18T12:59:15.629Z | call_stream | [4] Sending metadata
D 2022-05-18T12:59:15.629Z | channel | (1) dns:localhost:50052 Pick result for call [4]: QUEUE subchannel: null status: undefined undefined
D 2022-05-18T12:59:15.629Z | channel | (1) dns:localhost:50052 callRefTimer.ref | configSelectionQueue.length=0 pickQueue.length=1
D 2022-05-18T12:59:15.630Z | call_stream | [4] write() called with message of length 38
D 2022-05-18T12:59:15.630Z | call_stream | [4] end() called
D 2022-05-18T12:59:15.630Z | call_stream | [4] deferring writing data chunk of length 43
D 2022-05-18T12:59:15.630Z | pick_first | Connect to address list 127.0.0.1:50052
D 2022-05-18T12:59:15.631Z | subchannel_refcount | (3) 127.0.0.1:50052 refcount 1 -> 2
D 2022-05-18T12:59:15.631Z | pick_first | Start connecting to subchannel with address 127.0.0.1:50052
D 2022-05-18T12:59:15.631Z | pick_first | IDLE -> CONNECTING
D 2022-05-18T12:59:15.631Z | resolving_load_balancer | dns:localhost:50052 IDLE -> CONNECTING
D 2022-05-18T12:59:15.631Z | channel | (1) dns:localhost:50052 callRefTimer.unref | configSelectionQueue.length=0 pickQueue.length=0
D 2022-05-18T12:59:15.631Z | channel | (1) dns:localhost:50052 Pick result for call [4]: QUEUE subchannel: null status: undefined undefined
D 2022-05-18T12:59:15.631Z | channel | (1) dns:localhost:50052 callRefTimer.ref | configSelectionQueue.length=0 pickQueue.length=1
D 2022-05-18T12:59:15.631Z | connectivity_state | (1) dns:localhost:50052 IDLE -> CONNECTING
D 2022-05-18T12:59:15.632Z | subchannel | (3) 127.0.0.1:50052 IDLE -> CONNECTING
D 2022-05-18T12:59:15.632Z | pick_first | CONNECTING -> CONNECTING
D 2022-05-18T12:59:15.632Z | resolving_load_balancer | dns:localhost:50052 CONNECTING -> CONNECTING
D 2022-05-18T12:59:15.632Z | channel | (1) dns:localhost:50052 callRefTimer.unref | configSelectionQueue.length=0 pickQueue.length=0
D 2022-05-18T12:59:15.632Z | channel | (1) dns:localhost:50052 Pick result for call [4]: QUEUE subchannel: null status: undefined undefined
D 2022-05-18T12:59:15.632Z | channel | (1) dns:localhost:50052 callRefTimer.ref | configSelectionQueue.length=0 pickQueue.length=1
D 2022-05-18T12:59:15.632Z | connectivity_state | (1) dns:localhost:50052 CONNECTING -> CONNECTING
D 2022-05-18T12:59:15.633Z | subchannel | (3) 127.0.0.1:50052 creating HTTP/2 session
D 2022-05-18T12:59:15.650Z | subchannel | (3) 127.0.0.1:50052 connection closed with error self signed certificate
D 2022-05-18T12:59:15.650Z | subchannel | (3) 127.0.0.1:50052 connection closed
D 2022-05-18T12:59:15.650Z | subchannel | (3) 127.0.0.1:50052 CONNECTING -> TRANSIENT_FAILURE
D 2022-05-18T12:59:15.650Z | pick_first | CONNECTING -> TRANSIENT_FAILURE
D 2022-05-18T12:59:15.650Z | resolving_load_balancer | dns:localhost:50052 CONNECTING -> TRANSIENT_FAILURE
D 2022-05-18T12:59:15.650Z | channel | (1) dns:localhost:50052 callRefTimer.unref | configSelectionQueue.length=0 pickQueue.length=0
D 2022-05-18T12:59:15.650Z | channel | (1) dns:localhost:50052 Pick result for call [4]: TRANSIENT_FAILURE subchannel: null status: 14 No connection established
D 2022-05-18T12:59:15.650Z | call_stream | [4] cancelWithStatus code: 14 details: "No connection established"
D 2022-05-18T12:59:15.650Z | call_stream | [4] ended with status: code=14 details="No connection established"
D 2022-05-18T12:59:15.650Z | connectivity_state | (1) dns:localhost:50052 CONNECTING -> TRANSIENT_FAILURE
[2022-05-18T12:59:15.650Z] error: GRPC error when listening {"code":14,"details":"No connection established","metadata":{}}.
D 2022-05-18T12:59:15.650Z | call_stream | [4] cancelWithStatus code: 1 details: "Cancelled on client"
[2022-05-18T12:59:15.650Z] error: Streaming ended when listening.
D 2022-05-18T12:59:15.650Z | call_stream | [4] cancelWithStatus code: 1 details: "Cancelled on client"
[2022-05-18T12:59:15.650Z] error: Retry listening...
```
</details>

We cannot find the cause of the problem from the logs, any help is appreciated. Thank you!

**Comment by lauravuo** [comment]
Sorry for the late response, somehow I haven't noticed this issue before.

@tc-developer01 Are you still experiencing the issue? Do you have the TLS cert setting (ISSUER_TOOL_SERVER_CERT_PATH) pointing to the right path?

**Comment by thapld** [comment]
I also run with same problem, please help.
I also config ISSUER_TOOL_SERVER_CERT_PATH
